using DataAccess;
using DataAccess.Entities;
using Microsoft.EntityFrameworkCore;
using System.Text;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Navigation;
using System.Windows.Shapes;

namespace WpfApp1
{
    /// <summary>
    /// Interaction logic for MainWindow.xaml
    /// </summary>
    public partial class MainWindow : Window
    {
        public RestaurantDbContext context { get; set; }
        public MainWindow()
        {
            InitializeComponent();
            context = new RestaurantDbContext();
            menuDataGrid.AutoGeneratedColumns += AddToCartBtnColumn;
        }

        private void AddToCartBtnColumn(object? sender, EventArgs e)
        {
            AddButtonToDataContext();
        }

        private void myTabControl_SelectionChanged(object sender, SelectionChangedEventArgs e)
        {
            if (e.Source is TabControl)
            {
                if (myTabControl.SelectedItem is TabItem selectedTab)
                {
                    if (selectedTab.Header.ToString()=="Menu")
                    {
                        LoadMenuData();
                    }
                    else if (selectedTab.Header.ToString()=="Cart")
                    {
                        LoadMenuData();
                    }
                    else if (selectedTab.Header.ToString()== "Table Reservation")
                    {
                        LoadMenuData();
                    }
                }
            }
        }
        private void LoadMenuData()
        {
            var data = context.Products.Include(c => c.Category).Include(o=>o.Order).ToList();
            menuDataGrid.ItemsSource = data; 
        }
        private void AddButtonToDataContext()
        {
            var buttonColumn = new DataGridTemplateColumn
            {
                Header = "Add To Cart",
                Width = new DataGridLength(150)
            };

            var cellTemplate = new DataTemplate();
            var buttonFactory = new FrameworkElementFactory(typeof(Button));

            buttonFactory.SetValue(Button.ContentProperty, "Add");
            buttonFactory.AddHandler(Button.ClickEvent, new RoutedEventHandler(AddToOrder_Click));

            cellTemplate.VisualTree = buttonFactory;
            buttonColumn.CellTemplate = cellTemplate;

            menuDataGrid.Columns.Add(buttonColumn);
        }

        private void AddToOrder_Click(object sender, RoutedEventArgs e)
        {
            MessageBox.Show("Succesfully Added to Cart");
        }
    }
}