using DataAccess;
using DataAccess.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.IdentityModel.Tokens;
using System.Collections.ObjectModel;
using System.Text;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Navigation;
using System.Windows.Shapes;

namespace WpfApp1
{
    /// <summary>
    /// Interaction logic for MainWindow.xaml
    /// </summary>
    public partial class MainWindow : Window
    {
        public RestaurantDbContext context { get; set; }
        public User LoggedInUser { get; set; }
        private ObservableCollection<Product> cartItems { get; set; }
        public MainWindow()
        {
            InitializeComponent();
            context = new RestaurantDbContext();
            cartItems = new ObservableCollection<Product>();

            cartDataGrid.ItemsSource = cartItems;
            menuDataGrid.AutoGeneratedColumns += AddToCartBtnColumn;
            LoggedInUser = new User();
        }

        private void AddToCartBtnColumn(object? sender, EventArgs e)
        {
            AddButtonToDataContext();
        }

        private void myTabControl_SelectionChanged(object sender, SelectionChangedEventArgs e)
        {
            if (e.Source is TabControl)
            {
                if (myTabControl.SelectedItem is TabItem selectedTab)
                {
                    if (selectedTab.Header.ToString()=="Menu")
                    {
                        LoadMenuData();
                    }
                    else if (selectedTab.Header.ToString()=="Cart")
                    {
                        cartDataGrid.Items.Refresh();
                    }
                    else if (selectedTab.Header.ToString()== "Table Reservation")
                    {
                        LoadReservationData();
                    }else if (selectedTab.Header.ToString()== "Order Status")
                    {
                        LoadOrderData();
                    }
                }
            }
        }
        private void LoadMenuData()
        {
            var data = context.Products.Include(c => c.Category).Include(o=>o.Order).ToList();
            menuDataGrid.ItemsSource = data; 
        }private void LoadOrderData()
        {
            var data = context.Orders.Include(o=>o.User).Include(o=>o.Products).ToList();
            orderDataGrid.ItemsSource = data; 
        }
        private void AddButtonToDataContext()
        {
            var btnExist = menuDataGrid.Columns.FirstOrDefault(b => b.Header?.ToString() == "Add To Cart");

            if (btnExist != null) { return; }

            var buttonColumn = new DataGridTemplateColumn
            {
                Header = "Add To Cart",
                Width = new DataGridLength(150)
            };

            var cellTemplate = new DataTemplate();
            var buttonFactory = new FrameworkElementFactory(typeof(Button));

            buttonFactory.SetValue(Button.ContentProperty, "Add");
            buttonFactory.AddHandler(Button.ClickEvent, new RoutedEventHandler(AddToOrder_Click));

            cellTemplate.VisualTree = buttonFactory;
            buttonColumn.CellTemplate = cellTemplate;

            menuDataGrid.Columns.Add(buttonColumn);
        }

        private void AddToOrder_Click(object sender, RoutedEventArgs e)
        {
            var button = sender as Button;
            if (button == null) return;

            var product = button.DataContext as Product;
            if (product == null) return;

            cartItems.Add(product);
            
            MessageBox.Show($"Product '{product.Name}' succesfully Added to Cart");
        }

        private void FinishOrder_Click(object sender, RoutedEventArgs e)
        {
            try
            {
                if (cartItems.Count == 0) { MessageBox.Show("No Products Added to the Cart!"); return; }

                var products = new List<Product>();
                foreach (var item in cartItems)
                {
                    products.Add(item);
                    MessageBox.Show(item.Name);
                }
                context.Orders.Add(
                    new Order
                    {
                        OrderDate = DateTime.Now,
                        Products = products,
                        UserId = LoggedInUser.Id,
                        Status = OrderStatus.New
                    }
                );
                context.SaveChanges();
                cartItems.Clear();
                MessageBox.Show($"Order succesfully created!");
            }
            catch (Exception ex)
            {
                MessageBox.Show(ex.Message);
            } 
        }
        private void LoadReservationData()
        {
            var data = context.Bookings.Include(u => u.User).ToList();
            reservationDataGrid.ItemsSource = data;

            reservationDataGrid.Items.Refresh();
        }

        private void DateReserve_Click(object sender, RoutedEventArgs e)
        {
            if (string.IsNullOrEmpty(dateFieldTxt.Text) || string.IsNullOrWhiteSpace(dateFieldTxt.Text)) { MessageBox.Show("Enter Correct Date!"); return; }


            string expectedFormat = "dd/MM/yyyy HH:mm:ss";
            DateTime resultDate;
            int numbOfTabels = 1;


            bool success = DateTime.TryParseExact(dateFieldTxt.Text, expectedFormat, System.Globalization.CultureInfo.InvariantCulture, System.Globalization.DateTimeStyles.None, out resultDate);
            if (!success)
            {
                MessageBox.Show($"Failed to convert your date, Please enter this format \n[{expectedFormat}]","Error",MessageBoxButton.OK,MessageBoxImage.Error); return;
            }

            else {
                try
                {
                    if (string.IsNullOrEmpty(tableNumberFieldTxt.Text) || string.IsNullOrWhiteSpace(tableNumberFieldTxt.Text)) { MessageBox.Show("Enter number of tables!"); return; }

                    int numbOfTables = int.Parse(tableNumberFieldTxt.Text);
                    if (numbOfTables < 0) { MessageBox.Show("Number of Tabels must be > 0!"); return; }
                }
                catch (Exception ex)
                {
                    MessageBox.Show(ex.Message);
                    return;
                }

                try
                {
                      
                    if (resultDate < DateTime.Now) { MessageBox.Show("Time must be in the future!"); return; }

                    context.Bookings.Add(
                       new Booking
                       {
                           UserId = LoggedInUser.Id,
                           BookingDate = resultDate,
                           AmountOfTables = numbOfTabels
                       }
                   );
                    context.SaveChanges();
                    MessageBox.Show("Booking was succesfully made!");
                }
                catch (Exception ex)
                {

                    MessageBox.Show(ex.Message);
                }
               
            }
        }
    }
}